### PR TITLE
support sbt 1.0

### PR DESCRIPTION
**Pull request by xuwei-k**
fix https://github.com/gilt/sbt-dependency-graph-sugar/issues/17

### CODE REVIEW

**Comment by xuwei-k** [comment]
ping @gheine

**Comment by gheine** [comment]
@xuwei-k released, let me know if it works. 

Releasing this was a lot trickier than I expected. I had to push another fix to get some of the pulled-in dependencies and plugins lined up between sbt versions. And I had to do the release in two steps, editing the scripted plugin in between. 

For 0.13.16, I needed `ScriptedPlugin.scriptedSettings` in the root build.sbt and `libraryDependencies += "org.scala-sbt" % "scripted-plugin" % sbtVersion.value` in project/plugins.sbt 

while for 1.0.4 I had to remove `ScriptedPlugin.scriptedSettings` and change to a scala-versioned dependency of scripted plugin `libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value`

Any ideas what I'm missing here?

**Comment by xuwei-k** [comment]
see https://github.com/sbt/sbt/blob/v0.13.16/notes/0.13.16.markdown#sbt-cross-building

I think just use "^ publishSigned"

**Comment by gheine** [comment]
The problem is that the library dependency for scripted-plugin is different between 0.13.x and 1.0.x, see http://www.scala-sbt.org/0.13/docs/Testing-sbt-plugins.html#step+2%3A+scripted-plugin and http://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html#step+2%3A+scripted-plugin 

The latter is scala-versioned ("org.scala-sbt" %% "scripted-plugin"), the former isn't. So I need to manually edit the dependency between releasing for 0.13 and for 1.0

**Comment by gheine** [comment]
Maybe @jvican has an idea?

**Pull request merged**
